### ISSUE TITLE
Not found in Play Store or F-Droid

### ISSUE THREAD

**Issue by rstarkov** [eugmes/headingcalculator#1]
Hi, your app is no longer listed on either Play Store or F-Droid - any chance you could add it back? It's my favourite heading calculator!

**Comment by eugmes** [comment]
Hi, the app was removed from the Play Store for not having a "feature image" and not having "child-directed declaration". It is fixed now. It should be possible to download the app from there again.

**Comment by MilkManzJourDaddy** [comment]
It's not in the F-Droid **MAIN** repo', but for whatever reason, was moved to their **archive** repo', which is included but **not** toggled on.  So, for build/version 1.0, just enable the F-Droid `archive` repo'.  

As far as v1.1, hopefully the anti-features of a `weak security signature` and `known security vulnerability` have been resolved.  F-Droid ***IS*** slow to build, but generally it does not take them anywhere near as long as since v1.1 of this app' was released. 

As far as people using F-Droid to de-Google®, I hope no explanation is needed; ***Ugggggh***!!!  In a EFB (E.F.B. = Electronic Flight Bag) it's bad enough, but app's like this could be integrated into a "Glass Cockpit" or EFIS (E.F.I.S. = Electronic Flight Information System) or maybe even a Flight Manager/Flight Director, et cetera, even if only exchanging information.  The KWIK EFIS app' suite (a.k.a. KWIK COMP), on F-Droid, works with i.e. Stratux ADS-B and I think there is even things like a project for an Open Source sensor for Carbon Monoxide that can tie-in.  If Google® wants in my cockpit, they can read whatever gets posted online, i.e. from an automated `MAYDAY` from a Carbon Monoxide alarm not cancelled.  

Anyway, hopefully this app' will be returned to F-Droid with v1.1.  

Thanks!  🍻

**Comment by eugmes** [comment]
@MilkManzJourDaddy I've never used F-Droid. Where can I see the info about the security vulnerability you are referring to?

**Comment by MilkManzJourDaddy** [comment]
https://f-droid.org/en/docs/Anti-Features/


https://f-droid.org/wiki/page/AntiFeatures


https://f-droid.org/wiki/page/Antifeature:KnownVuln

**Comment by MilkManzJourDaddy** [comment]
https://f-droid.org/en/docs/Anti-Features/#KnownVuln

**Comment by eugmes** [comment]
I see it mentioned in the page history here: https://f-droid.org/wiki/index.php?title=org.debian.eugen.headingcalculator&diff=218388&oldid=211685 . There are not too many details there :/ .
Was it just weak APK signature due to package being too old, or something in actual code?

**Comment by MilkManzJourDaddy** [comment]
It might be that the older "weak" signature triggers both `AntiFeatures`.  I asked in an unofficial online community for F-Droid.  But no response yet.  `¯_(ツ)_/¯`  IDK, after you update the signature and whatnot, I assume someone will have to submit a request.  

Here are a few links that may help: 

[FAQ - App Developers](https://f-droid.org/en/docs/FAQ_-_App_Developers/)

[Help: Update My App'?](https://forum.f-droid.org/t/help-update-my-app/7935)

[Requests For Packaging](https://gitlab.com/fdroid/rfp)

> Submitting to F-Droid: Quick Start Guide — by Andy Balaam, original at [artificialworlds.net](http://www.artificialworlds.net/blog/2017/01/17/submitting-a-package-to-f-droid/)  .  >   
> Doing this is apparently the best way to get your own package into the repository, since you can provide a direct merge request for the metadata about your package, making it easy for the maintainers.
> https://fdroid.gitlab.io/fdroid-website/docs/Submitting_to_F-Droid_Quick_Start_Guide/

**Comment by MilkManzJourDaddy** [comment]
By the way, the info' is missing for many app's, but I recommend populating the `links` fields, including a `changelog`, any `website`, or `donation_link`, or whatever else is appropriate and acceptable.

**Comment by eugmes** [comment]
It seems the app is now available on F-Droid too, so I'm closing this issue.
